DROP TABLE IF EXISTS event_gap_overlap CASCADE;
DROP TABLE IF EXISTS event_policy CASCADE;
DROP TABLE IF EXISTS flight_stats CASCADE;
DROP TABLE IF EXISTS flight CASCADE;
DROP TABLE IF EXISTS scenario_stats CASCADE;
DROP TABLE IF EXISTS scenario CASCADE;
DROP TABLE IF EXISTS policy CASCADE;
